### PR TITLE
fix the sourcemap

### PR DESCRIPTION
**Pull request by paulirish**
We're using this site to try out some new sourcemap functionality in devtools

Turns out the map was a little dated and incorrect.

This was the result of me doing a basic `sass s.scss:s.css` with `Sass 3.4.19 (Selective Steve)`

### CODE REVIEW

**Comment by paulirish** [comment]
cc @aslushnikov

**Comment by kaelig** [comment]
Cheers! Thank you very much. I've re-compiled with the latest version of Sass (just in case), and pushed that to master.

**Comment by paulirish** [comment]
Cool. Is there a difference between the code in your PR and your commit?

**Comment by kaelig** [comment]
Not sure, I haven't thought of checking.

**Comment by paulirish** [comment]
k. i was just curious why you didn't merge my PR. :)

We did some further testing over here with that output, so I'll have to repeat with your commit.

**Comment by paulirish** [comment]
The difference between the two:
image

Not bad. Guessing some bugfixes in the sourcemap generation that's inbetween whatever compiler you used (what version?) and what I used.

**Comment by kaelig** [comment]
Interesting! I used Sass v3.4.22. Nothing in their release notes mentions any fixes regarding sourcemaps, so why this changed is a mystery to me.

**Pull request closed without merging**
